 version: '3.4'

 services:
   db:
     user: root
     image: mcr.microsoft.com/mssql/server:2019-latest
     environment:
       ACCEPT_EULA: "Y"
       SA_PASSWORD: "sql@123456"
       MSSQL_PID: Express
     ports:
       - "1433:1433"
     volumes:
       - C:\dados\volumes\sqlserver\Fiap_Fase1_TechChallenge_Contatos:/var/opt/mssql/data
     networks:
       - minha-rede
   redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - minha-rede
   regionalcontacts.api:
    image: ${DOCKER_REGISTRY-}regionalcontactsapi
    environment:
      - ASPNETCORE_URLS=http://+:80
    build:
      context: .
      dockerfile: src/RegionalContacts.Api/Dockerfile      
    ports:
      - "5001:80"
    depends_on:
      - db
      - redis
    networks:
       - minha-rede

   prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - minha-rede
    ports:
      - 9090:9090
   node-exporter:
    image: prom/node-exporter
    networks:
      - minha-rede
    ports:
      - 9100:9100

 networks:
   minha-rede:

 volumes:
   db-data: