apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc-datasources
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc-dashboards
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
