apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-datasources-pv
  namespace: monitoring
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: C:\dados\volumes\grafana\provisioning\datasources  # Diretório local
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-dashboards-pv
  namespace: monitoring
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: C:\dados\volumes\grafana\provisioning\dashboards  # Diretório local
