apiVersion: apps/v1
kind: Deployment
metadata:
  name: consulting-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consulting-api
  template:
    metadata:
      labels:
        app: consulting-api
    spec:
      containers:
      - name: consulting-api
        image: 318914/consultingapi:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:80"
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: consulting-api
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
  selector:
    app: consulting-api