apiVersion: apps/v1
kind: Deployment
metadata:
  name: create-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: create-api
  template:
    metadata:
      labels:
        app: create-api
    spec:
      containers:
      - name: create-api
        image: danielharo/regional-contacts-api-create.api:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:80"
---
apiVersion: v1
kind: Service
metadata:
  name: create-api
spec:
  type: NodePort  # Usando NodePort para acesso local
  selector:
    app: create-api
  ports:
    - port: 80           # Porta exposta no serviço
      targetPort: 80      # Porta onde a aplicação está ouvindo no pod
      nodePort: 30081     # Porta exposta no nó local (seu computador)
