apiVersion: apps/v1
kind: Deployment
metadata:
  name: delete-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delete-api
  template:
    metadata:
      labels:
        app: delete-api
    spec:
      containers:
      - name: delete-api
        image: deleteapi
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:80"
---
apiVersion: v1
kind: Service
metadata:
  name: delete-api
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: delete-api
