apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-delete
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-delete
  template:
    metadata:
      labels:
        app: worker-delete
    spec:
      containers:
      - name: worker-delete
        image: workerdelete
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:80"
---
apiVersion: v1
kind: Service
metadata:
  name: worker-delete
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: worker-delete
