global:
  scrape_interval: 10s
scrape_configs:
 - job_name: prometheus
   static_configs:
    - targets:
       - prometheus:9090
 - job_name: node
   static_configs:
    - targets:
       - node-exporter:9100
 - job_name: consulting-api
   metrics_path: /metrics
   static_configs:
    - targets: ['host.docker.internal:5001']
 - job_name: create-api
   metrics_path: /metrics
   static_configs:
    - targets: ['host.docker.internal:5002']    
 - job_name: update-api
   metrics_path: /metrics
   static_configs:
    - targets: ['host.docker.internal:5003']    
 - job_name: delete-api
   metrics_path: /metrics
   static_configs:
    - targets: ['host.docker.internal:5004']
 - job_name: create-worker
   metrics_path: /metrics
   static_configs:
    - targets: ['host.docker.internal:5005']
 - job_name: delete-worker
   metrics_path: /metrics
   static_configs:
    - targets: ['host.docker.internal:5006']
 - job_name: update-worker
   metrics_path: /metrics
   static_configs:
    - targets: ['host.docker.internal:5007']