apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s  # Definindo o scrape_interval global

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['prometheus:9090']
      - job_name: 'node'
        static_configs:
          - targets: ['node-exporter:9100']
      - job_name: 'consulting-api'
        metrics_path: /metrics
        static_configs:
          - targets: ['consulting-api:80']
      - job_name: 'create-api'
        metrics_path: /metrics
        static_configs:
          - targets: ['create-api:80']
      - job_name: 'update-api'
        metrics_path: /metrics
        static_configs:
          - targets: ['update-api:80']
      - job_name: 'delete-api'
        metrics_path: /metrics
        static_configs:
          - targets: ['delete-api:80']
      - job_name: 'create-worker'
        metrics_path: /metrics
        static_configs:
          - targets: ['create-worker:80']
      - job_name: 'delete-worker'
        metrics_path: /metrics
        static_configs:
          - targets: ['delete-worker:80']
      - job_name: 'update-worker'
        metrics_path: /metrics
        static_configs:
          - targets: ['update-worker:80']
