{
 "title": "RegionalContacts.API Metrics Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Painel ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Successful Responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  microsoft_aspnetcore_hosting_http_server_request_duration_count{\n    http_response_status_code=~\"2..\",\n    http_route=\"api/Contact\",\n    instance=\"host.docker.internal:5001\",\n    job=\"contatos-api\",\n    network_protocol_version=\"1.1\",\n    url_scheme=\"http\"\n  }\n) or vector(0)"
    }
   ]
  },
  {
   "title": "Client Error Responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  microsoft_aspnetcore_hosting_http_server_request_duration_count{\n    http_response_status_code=~\"4..\",\n    http_route=\"api/Contact\",\n    instance=\"host.docker.internal:5001\",\n    job=\"contatos-api\",\n    network_protocol_version=\"1.1\",\n    url_scheme=\"http\"\n  }\n) or vector(0)"
    }
   ]
  },
  {
   "title": "Server Error Responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  microsoft_aspnetcore_hosting_http_server_request_duration_count{\n    http_response_status_code=~\"5..\",\n    http_route=\"api/Contact\",\n    instance=\"host.docker.internal:5001\",\n    job=\"contatos-api\",\n    network_protocol_version=\"1.1\",\n    url_scheme=\"http\"\n  }\n) or vector(0)"
    }
   ]
  },
  {
   "title": "Total Request's",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(\n    microsoft_aspnetcore_hosting_http_server_request_duration_count{\n      http_response_status_code=~\"2..\",\n      http_route=\"api/Contact\",\n      instance=\"host.docker.internal:5001\",\n      job=\"contatos-api\",\n      network_protocol_version=\"1.1\",\n      url_scheme=\"http\"\n    }\n  ) or vector(0)\n) +\n(\n  sum(\n    microsoft_aspnetcore_hosting_http_server_request_duration_count{\n      http_response_status_code=~\"4..\",\n      http_route=\"api/Contact\",\n      instance=\"host.docker.internal:5001\",\n      job=\"contatos-api\",\n      network_protocol_version=\"1.1\",\n      url_scheme=\"http\"\n    }\n  ) or vector(0)\n) +\n(\n  sum(\n    microsoft_aspnetcore_hosting_http_server_request_duration_count{\n      http_response_status_code=~\"5..\",\n      http_route=\"api/Contact\",\n      instance=\"host.docker.internal:5001\",\n      job=\"contatos-api\",\n      network_protocol_version=\"1.1\",\n      url_scheme=\"http\"\n    }\n  ) or vector(0)\n)\n"
    }
   ]
  },
  {
   "title": "Process Virtual Memory Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=\"host.docker.internal:5001\", job=\"contatos-api\"}"
    }
   ]
  },
  {
   "title": "No Of Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "process_num_threads{instance=\"host.docker.internal:5001\", job=\"contatos-api\"}"
    }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(http_requests_received_total{}[$__interval])"
    }
   ]
  }
 ]
}