name: CI/CD Build and Run Docker Container

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t regionalcontacts.api:latest -f ./src/RegionalContacts.Api/Dockerfile .

    - name: Tag Docker image
      run: |
        docker tag regionalcontacts.api:latest ${{ secrets.DOCKER_USERNAME }}/regionalcontacts.api:latest

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/regionalcontacts.api:latest

  test-unitario:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Restore dependencies
      run: dotnet restore tests/RegionalContacts.Tests/RegionalContacts.Tests.csproj

    - name: Build solution
      run: dotnet build tests/RegionalContacts.Tests/RegionalContacts.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test tests/RegionalContacts.Tests/RegionalContacts.Tests.csproj

  test-integracao:
    runs-on: self-hosted
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore tests/RegionalContacts.Integration.Tests/RegionalContacts.Integration.Tests.csproj

    - name: Build solution
      run: dotnet build tests/RegionalContacts.Integration.Tests/RegionalContacts.Integration.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      env:
        ConnectionStrings__ConnectionString: "Data Source=host.docker.internal,1533;Initial Catalog=Fiap_Fase1_TechChallenge_Contatos;User ID=sa;Password=sql@123456;Connect Timeout=30;Encrypt=False;Trust Server Certificate=True;Application Intent=ReadWrite;Multi Subnet Failover=False"
        Redis__Port: 6380
      run: dotnet test tests/RegionalContacts.Integration.Tests/RegionalContacts.Integration.Tests.csproj

  deploy:
    runs-on: ubuntu-latest
    needs: test-integracao
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker Compose image
      run: |
        docker-compose -f ./docker-compose.yml build
        docker-compose -f ./docker-compose.yml push

    - name: Run Docker Compose
      run: |
        docker-compose -f ./docker-compose.yml up -d

    - name: Verify Docker containers are running
      run: docker ps -a